version: '3'
services:

  db:
    image: postgis/postgis:13-3.1
    container_name: postgis-eiel
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: sig_local
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - pgdata-tfg:/var/lib/postgresql/data
    ports:
      - "9003:5432"

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  tegola-mvt-postgis-provider:
    image: gospatial/tegola:v0.16.0
    container_name: tegola-mvt-postgis-provider
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - 9005:8080
    volumes:
      - ./tegola:/data
    command: >
      serve --config /data/config.toml
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sig_local
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  pgdata-tfg:
