export const LABELS = {
    "open_street_map": "Open Street Map",
    "orthophoto": "Ortofotografía",
    "dist2022": "Distritos",
    "muni2022": "Municipios",
    "nucleos": "Núcleos",
    "masa": "Manzanas",
    "parcela": "Parcela",
    "subparce": "Subparcela",
    "constru": "Construcción",
    "gdie_g_calles": "Ejes de vía",
    "n_policia": "Números de policía",
    "bomberos": "Bomberos",
    "proteccioncivil": "Protección Civil",
    "mercado": "Mercados",
    "centrocom": "Centros comerciales",
    "mercadillos": "Mercadillos",
    "hipermercados": "Hipermercados",
    "galimenta": "Galerías de alimentación",
    "comerespecial": "Comercio especial",
    "parquesocio": "Parques ocio",
    "parques": "Parques",
    "puntoslim": "Puntos limpios",
    "peligrosos": "Residuos peligrosos",
    "vertederos": "Vertederos",
    "ssociales": "Servicios sociales",
    "inmigrantes": "Centros inmigrantes",
    "hospital": "Hospitales",
    "saludmental": "Salud mental",
    "consultoriosalud": "Consultorios salud",
    "centrosalud": "Centros salud",
    "centroespecialidades": "Centros especialidades",
    "drogodependencia": "Drogodependencia",
    "saludotros": "Otros centros de salud",
    "educapu": "Centros educativos públicos",
    "educase": "Centros educativos secundaria",
    "colegiosmayores": "Colegios mayores",
    "univers": "Universidades",
    "parroquias": "Parroquias",
    "plazastoros": "Plazas de toros",
    "museos": "Museos",
    "cines": "Cines",
    "galerias": "Galerías de arte",
    "centrolectura": "Centros de lectura",
    "librerias": "Librerías",
    "bibliometro": "Bibliometro",
    "biblimunicipal": "Biblioteca municipales",
    "bibliobus": "Bibliobuses",
    "teatros": "Teatros",
    "nmcl_deporte": "Instalaciones deportivas",
    "nmcl_deporteotros": "Otras Instala. Deportivas",
    "nmcl_imder": "Institutos deporte",
    "casas_consistoriales": "Casas consistoriales",
    "cementerios": "Cementerios",
    "equipamientos_municipales": "Equipamientos municipales",
    "mi_casas_consistoriales": "Casa consistorial",
    "mi_cementerios": "Cementerio",
    "mi_centros_asistencia": "Centro asistencial",
    "mi_centros_ensenanza": "Centro de enseñanza",
    "mi_centros_sanitarios": "Centro sanitario",
    "mi_centros_culturales": "Centro cultural",
    "mi_edificios_sin_uso": "Edificio público sin uso",
    "mi_instalaciones_deportivas": "Instalación deportiva",
    "mi_lonja_merca_feria": "Lonja o mercado o feria",
    "mi_mataderos": "Matadero",
    "mi_parques": "Parque",
    "mi_tanatorios": "Tanatorio",
    "mi_proteccion_civil": "Protección civil",
    "mi_vertederos": "Vertido encuestado",
}